# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 14:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickSpy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(null=True, protocol='IPv4')),
            ],
            options={
                'verbose_name': 'Registered Entry',
                'verbose_name_plural': 'Registered Entries',
            },
        ),
        migrations.CreateModel(
            name='GrivURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=254)),
                ('shortcode', models.CharField(blank=True, max_length=16, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_clicked', models.DateTimeField(blank=True, null=True)),
                ('clicks', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('inspection', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
            },
        ),
        migrations.AddField(
            model_name='clickspy',
            name='url_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.GrivURL'),
        ),
    ]
