# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 12:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrivURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=254, validators=[django.core.validators.URLValidator])),
                ('shortcode', models.CharField(blank=True, max_length=16, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_clicked', models.DateTimeField(blank=True)),
                ('quantity', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
