# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grivurl',
            name='last_clicked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
