# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20170709_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grivurl',
            name='url',
            field=models.URLField(max_length=254),
        ),
    ]
