# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20170709_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickSpy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(null=True, protocol='IPv4')),
            ],
        ),
        migrations.AddField(
            model_name='grivurl',
            name='inspection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clickspy',
            name='url_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.GrivURL'),
        ),
    ]
