# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20170630_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='grivurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='grivurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
