# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20170711_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clickspy',
            options={'verbose_name': 'Registered Entry', 'verbose_name_plural': 'Registered Entries'},
        ),
        migrations.AlterModelOptions(
            name='grivurl',
            options={'verbose_name': 'URL', 'verbose_name_plural': 'URLs'},
        ),
    ]
